//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubStringCounter.Client.ServiceReferenceTest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceTest.IStringOccurrence")]
    public interface IStringOccurrence {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringOccurrence/CountSubString", ReplyAction="http://tempuri.org/IStringOccurrence/CountSubStringResponse")]
        int CountSubString(string original, string substring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringOccurrence/CountSubString", ReplyAction="http://tempuri.org/IStringOccurrence/CountSubStringResponse")]
        System.Threading.Tasks.Task<int> CountSubStringAsync(string original, string substring);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStringOccurrenceChannel : SubStringCounter.Client.ServiceReferenceTest.IStringOccurrence, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StringOccurrenceClient : System.ServiceModel.ClientBase<SubStringCounter.Client.ServiceReferenceTest.IStringOccurrence>, SubStringCounter.Client.ServiceReferenceTest.IStringOccurrence {
        
        public StringOccurrenceClient() {
        }
        
        public StringOccurrenceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StringOccurrenceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringOccurrenceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringOccurrenceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CountSubString(string original, string substring) {
            return base.Channel.CountSubString(original, substring);
        }
        
        public System.Threading.Tasks.Task<int> CountSubStringAsync(string original, string substring) {
            return base.Channel.CountSubStringAsync(original, substring);
        }
    }
}
