//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataConvert.Client.ServiceReferenceTest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceTest.IConvertService")]
    public interface IConvertService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConvertService/Convert", ReplyAction="http://tempuri.org/IConvertService/ConvertResponse")]
        string Convert(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConvertService/Convert", ReplyAction="http://tempuri.org/IConvertService/ConvertResponse")]
        System.Threading.Tasks.Task<string> ConvertAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConvertServiceChannel : DataConvert.Client.ServiceReferenceTest.IConvertService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConvertServiceClient : System.ServiceModel.ClientBase<DataConvert.Client.ServiceReferenceTest.IConvertService>, DataConvert.Client.ServiceReferenceTest.IConvertService {
        
        public ConvertServiceClient() {
        }
        
        public ConvertServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConvertServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Convert(System.DateTime date) {
            return base.Channel.Convert(date);
        }
        
        public System.Threading.Tasks.Task<string> ConvertAsync(System.DateTime date) {
            return base.Channel.ConvertAsync(date);
        }
    }
}
